-- Table: public.superheroes_power_matrix

-- DROP TABLE IF EXISTS public.superheroes_power_matrix;

CREATE TABLE IF NOT EXISTS public.superheroes_power_matrix
(
    "Name" character varying COLLATE pg_catalog."default",
    "Agility" character varying COLLATE pg_catalog."default",
    "Accelerated Healing" character varying COLLATE pg_catalog."default",
    "Lantern Power Ring" character varying COLLATE pg_catalog."default",
    "Dimensional Awareness" character varying COLLATE pg_catalog."default",
    "Cold Resistance" character varying COLLATE pg_catalog."default",
    "Durability" character varying COLLATE pg_catalog."default",
    "Stealth" character varying COLLATE pg_catalog."default",
    "Energy Absorption" character varying COLLATE pg_catalog."default",
    "Flight" character varying COLLATE pg_catalog."default",
    "Danger Sense" character varying COLLATE pg_catalog."default",
    "Underwater breathing" character varying COLLATE pg_catalog."default",
    "Marksmanship" character varying COLLATE pg_catalog."default",
    "Weapons Master" character varying COLLATE pg_catalog."default",
    "Power Augmentation" character varying COLLATE pg_catalog."default",
    "Animal Attributes" character varying COLLATE pg_catalog."default",
    "Longevity" character varying COLLATE pg_catalog."default",
    "Intelligence" character varying COLLATE pg_catalog."default",
    "Super Strength" character varying COLLATE pg_catalog."default",
    "Cryokinesis" character varying COLLATE pg_catalog."default",
    "Telepathy" character varying COLLATE pg_catalog."default",
    "Energy Armor" character varying COLLATE pg_catalog."default",
    "Energy Blasts" character varying COLLATE pg_catalog."default",
    "Duplication" character varying COLLATE pg_catalog."default",
    "Size Changing" character varying COLLATE pg_catalog."default",
    "Density Control" character varying COLLATE pg_catalog."default",
    "Stamina" character varying COLLATE pg_catalog."default",
    "Astral Travel" character varying COLLATE pg_catalog."default",
    "Audio Control" character varying COLLATE pg_catalog."default",
    "Dexterity" character varying COLLATE pg_catalog."default",
    "Omnitrix" character varying COLLATE pg_catalog."default",
    "Super Speed" character varying COLLATE pg_catalog."default",
    "Possession" character varying COLLATE pg_catalog."default",
    "Animal Oriented Powers" character varying COLLATE pg_catalog."default",
    "Weapon-based Powers" character varying COLLATE pg_catalog."default",
    "Electrokinesis" character varying COLLATE pg_catalog."default",
    "Darkforce Manipulation" character varying COLLATE pg_catalog."default",
    "Death Touch" character varying COLLATE pg_catalog."default",
    "Teleportation" character varying COLLATE pg_catalog."default",
    "Enhanced Senses" character varying COLLATE pg_catalog."default",
    "Telekinesis" character varying COLLATE pg_catalog."default",
    "Energy Beams" character varying COLLATE pg_catalog."default",
    "Magic" character varying COLLATE pg_catalog."default",
    "Hyperkinesis" character varying COLLATE pg_catalog."default",
    "Jump" character varying COLLATE pg_catalog."default",
    "Clairvoyance" character varying COLLATE pg_catalog."default",
    "Dimensional Travel" character varying COLLATE pg_catalog."default",
    "Power Sense" character varying COLLATE pg_catalog."default",
    "Shapeshifting" character varying COLLATE pg_catalog."default",
    "Peak Human Condition" character varying COLLATE pg_catalog."default",
    "Immortality" character varying COLLATE pg_catalog."default",
    "Camouflage" character varying COLLATE pg_catalog."default",
    "Element Control" character varying COLLATE pg_catalog."default",
    "Phasing" character varying COLLATE pg_catalog."default",
    "Astral Projection" character varying COLLATE pg_catalog."default",
    "Electrical Transport" character varying COLLATE pg_catalog."default",
    "Fire Control" character varying COLLATE pg_catalog."default",
    "Projection" character varying COLLATE pg_catalog."default",
    "Summoning" character varying COLLATE pg_catalog."default",
    "Enhanced Memory" character varying COLLATE pg_catalog."default",
    "Reflexes" character varying COLLATE pg_catalog."default",
    "Invulnerability" character varying COLLATE pg_catalog."default",
    "Energy Constructs" character varying COLLATE pg_catalog."default",
    "Force Fields" character varying COLLATE pg_catalog."default",
    "Self-Sustenance" character varying COLLATE pg_catalog."default",
    "Anti-Gravity" character varying COLLATE pg_catalog."default",
    "Empathy" character varying COLLATE pg_catalog."default",
    "Power Nullifier" character varying COLLATE pg_catalog."default",
    "Radiation Control" character varying COLLATE pg_catalog."default",
    "Psionic Powers" character varying COLLATE pg_catalog."default",
    "Elasticity" character varying COLLATE pg_catalog."default",
    "Substance Secretion" character varying COLLATE pg_catalog."default",
    "Elemental Transmogrification" character varying COLLATE pg_catalog."default",
    "Technopath/Cyberpath" character varying COLLATE pg_catalog."default",
    "Photographic Reflexes" character varying COLLATE pg_catalog."default",
    "Seismic Power" character varying COLLATE pg_catalog."default",
    "Animation" character varying COLLATE pg_catalog."default",
    "Precognition" character varying COLLATE pg_catalog."default",
    "Mind Control" character varying COLLATE pg_catalog."default",
    "Fire Resistance" character varying COLLATE pg_catalog."default",
    "Power Absorption" character varying COLLATE pg_catalog."default",
    "Enhanced Hearing" character varying COLLATE pg_catalog."default",
    "Nova Force" character varying COLLATE pg_catalog."default",
    "Insanity" character varying COLLATE pg_catalog."default",
    "Hypnokinesis" character varying COLLATE pg_catalog."default",
    "Animal Control" character varying COLLATE pg_catalog."default",
    "Natural Armor" character varying COLLATE pg_catalog."default",
    "Intangibility" character varying COLLATE pg_catalog."default",
    "Enhanced Sight" character varying COLLATE pg_catalog."default",
    "Molecular Manipulation" character varying COLLATE pg_catalog."default",
    "Heat Generation" character varying COLLATE pg_catalog."default",
    "Adaptation" character varying COLLATE pg_catalog."default",
    "Gliding" character varying COLLATE pg_catalog."default",
    "Power Suit" character varying COLLATE pg_catalog."default",
    "Mind Blast" character varying COLLATE pg_catalog."default",
    "Probability Manipulation" character varying COLLATE pg_catalog."default",
    "Gravity Control" character varying COLLATE pg_catalog."default",
    "Regeneration" character varying COLLATE pg_catalog."default",
    "Light Control" character varying COLLATE pg_catalog."default",
    "Echolocation" character varying COLLATE pg_catalog."default",
    "Levitation" character varying COLLATE pg_catalog."default",
    "Toxin and Disease Control" character varying COLLATE pg_catalog."default",
    "Banish" character varying COLLATE pg_catalog."default",
    "Energy Manipulation" character varying COLLATE pg_catalog."default",
    "Heat Resistance" character varying COLLATE pg_catalog."default",
    "Natural Weapons" character varying COLLATE pg_catalog."default",
    "Time Travel" character varying COLLATE pg_catalog."default",
    "Enhanced Smell" character varying COLLATE pg_catalog."default",
    "Illusions" character varying COLLATE pg_catalog."default",
    "Thirstokinesis" character varying COLLATE pg_catalog."default",
    "Hair Manipulation" character varying COLLATE pg_catalog."default",
    "Illumination" character varying COLLATE pg_catalog."default",
    "Omnipotent" character varying COLLATE pg_catalog."default",
    "Cloaking" character varying COLLATE pg_catalog."default",
    "Changing Armor" character varying COLLATE pg_catalog."default",
    "Power Cosmic" character varying COLLATE pg_catalog."default",
    "Biokinesis" character varying COLLATE pg_catalog."default",
    "Water Control" character varying COLLATE pg_catalog."default",
    "Radiation Immunity" character varying COLLATE pg_catalog."default",
    "Vision - Telescopic" character varying COLLATE pg_catalog."default",
    "Toxin and Disease Resistance" character varying COLLATE pg_catalog."default",
    "Spatial Awareness" character varying COLLATE pg_catalog."default",
    "Energy Resistance" character varying COLLATE pg_catalog."default",
    "Telepathy Resistance" character varying COLLATE pg_catalog."default",
    "Molecular Combustion" character varying COLLATE pg_catalog."default",
    "Omnilingualism" character varying COLLATE pg_catalog."default",
    "Portal Creation" character varying COLLATE pg_catalog."default",
    "Magnetism" character varying COLLATE pg_catalog."default",
    "Mind Control Resistance" character varying COLLATE pg_catalog."default",
    "Plant Control" character varying COLLATE pg_catalog."default",
    "Sonar" character varying COLLATE pg_catalog."default",
    "Sonic Scream" character varying COLLATE pg_catalog."default",
    "Time Manipulation" character varying COLLATE pg_catalog."default",
    "Enhanced Touch" character varying COLLATE pg_catalog."default",
    "Magic Resistance" character varying COLLATE pg_catalog."default",
    "Invisibility" character varying COLLATE pg_catalog."default",
    "Sub-Mariner" character varying COLLATE pg_catalog."default",
    "Radiation Absorption" character varying COLLATE pg_catalog."default",
    "Intuitive aptitude" character varying COLLATE pg_catalog."default",
    "Vision - Microscopic" character varying COLLATE pg_catalog."default",
    "Melting" character varying COLLATE pg_catalog."default",
    "Wind Control" character varying COLLATE pg_catalog."default",
    "Super Breath" character varying COLLATE pg_catalog."default",
    "Wallcrawling" character varying COLLATE pg_catalog."default",
    "Vision - Night" character varying COLLATE pg_catalog."default",
    "Vision - Infrared" character varying COLLATE pg_catalog."default",
    "Grim Reaping" character varying COLLATE pg_catalog."default",
    "Matter Absorption" character varying COLLATE pg_catalog."default",
    "The Force" character varying COLLATE pg_catalog."default",
    "Resurrection" character varying COLLATE pg_catalog."default",
    "Terrakinesis" character varying COLLATE pg_catalog."default",
    "Vision - Heat" character varying COLLATE pg_catalog."default",
    "Vitakinesis" character varying COLLATE pg_catalog."default",
    "Radar Sense" character varying COLLATE pg_catalog."default",
    "Qwardian Power Ring" character varying COLLATE pg_catalog."default",
    "Weather Control" character varying COLLATE pg_catalog."default",
    "Vision - X-Ray" character varying COLLATE pg_catalog."default",
    "Vision - Thermal" character varying COLLATE pg_catalog."default",
    "Web Creation" character varying COLLATE pg_catalog."default",
    "Reality Warping" character varying COLLATE pg_catalog."default",
    "Odin Force" character varying COLLATE pg_catalog."default",
    "Symbiote Costume" character varying COLLATE pg_catalog."default",
    "Speed Force" character varying COLLATE pg_catalog."default",
    "Phoenix Force" character varying COLLATE pg_catalog."default",
    "Molecular Dissipation" character varying COLLATE pg_catalog."default",
    "Vision - Cryo" character varying COLLATE pg_catalog."default",
    "Omnipresent" character varying COLLATE pg_catalog."default",
    "Omniscient" character varying COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.superheroes_power_matrix
    OWNER to postgres;